name: Node.js CI

on:
   push:
      branches: ['**']
   pull_request:
      branches: ['main']

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
         DISCORD_TEST_TOKEN: ${{ secrets.DISCORD_TEST_TOKEN }}
         GUILD_ID: ${{ secrets.GUILD_ID }}
         CLIENT_ID: ${{ secrets. }}
         MONGODB_URI: ${{ secrets.CLIENT_ID }}
         DEV_ID_1: ${{ secrets.MONGODB_URI }}
         DEV_ID_2: ${{ secrets.DEV_ID_2 }}

      strategy:
         matrix:
            node-version: [22.x]

      steps:
         - uses: actions/checkout@v4
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v3
           with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
         - run: npm ci
         - run: npm start
