name: Switch Discord Token

on:
   push:
      branches:
         - main

jobs:
   switch-token:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v4

         - name: Check Token Status
           id: check-token
           run: |
              if grep -q '// client.login(process.env.DISCORD_TOKEN);' src/index.ts && grep -q 'client.login(process.env.DISCORD_TEST_TOKEN);' src/index.ts; then
                echo "::set-output name=should_switch::true"
              else
                echo "::set-output name=should_switch::false"
              fi

         - name: Switch Discord Token
           if: steps.check-token.outputs.should_switch == 'true'
           run: |
              sed -i 's/\/\/ client.login(process.env.DISCORD_TOKEN);/client.login(process.env.DISCORD_TOKEN);/' src/index.ts
              sed -i 's/client.login(process.env.DISCORD_TEST_TOKEN);/\/\/ client.login(process.env.DISCORD_TEST_TOKEN);/' src/index.ts

         - name: Commit and Push Changes
           if: steps.check-token.outputs.should_switch == 'true'
           run: |
              git config --global user.email "${{ secrets.USER_EMAIL }}"
              git config --global user.name "${{ secrets.USER_NAME }}"
              git add src/index.ts
              git commit -m "Switch to Discord production token"
              git push
